name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Run Tests
        run: make test

  cypress-run:
    runs-on: ubuntu-latest
    needs: build  # Ajoutez cette ligne si le job build est nécessaire avant cypress-run
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Utilisez la version de Node.js que vous utilisez dans votre projet

      - name: Install dependencies
        run: npm install  # ou yarn install si vous utilisez Yarn

      - name: Run Cypress tests in headless mode
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e  # Remplacez par votre commande de test Cypress
          start: npm start  # Remplacez par la commande pour démarrer votre application
          wait-on: 'http://localhost:8080'  # Remplacez par l'URL de votre application
          browser: chrome  # Vous pouvez spécifier le navigateur à utiliser
          headless: true  # Active le mode headless
