name: Makefile CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies via Composer
      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      # Install project dependencies using the Makefile
      - name: Run install target (composer install)
        run: make install

      # Run tests
      - name: Run PHPUnit tests
        run: make test

      # Run linting checks
      - name: Run lint checks
        run: make lint
