name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: make install

      - name: Run Tests
        run: make test

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'  # Utilisez la version de Node.js que vous utilisez dans votre projet

      - name: Install dependencies
        run: npm install  # ou yarn install si vous utilisez Yarn

      - name: Run Cypress tests
        run: npx cypress run  # Exécute les tests en mode headless
        env:
          CYPRESS_baseUrl: http://localhost:8080  # Assurez-vous que votre application est accessible à cette URL

